### PR TITLE
KHAYAAL-30-page-activity-pr

### PR DESCRIPTION
**Pull request by AdityaTanejaRox**
Please accept PR

### CODE REVIEW

**Comment by roshan1999** [comment]
Hi Aditya please put screenshot

**Comment by AdityaTanejaRox** [comment]
For mobile : - 
image


for laptop : - Its still wrapping...
image

**Comment by roshan1999** [comment]
You need to make change to your css file

**Comment by AdityaTanejaRox** [comment]
hi, please  accept the pr, so that  Nameerah can begin her work

**Pull request merged**
