### PR TITLE
KHAYAAL-30-new-activity-page-component

### PR DESCRIPTION
**Pull request by AdityaTanejaRox**
Sanity for the above : - 

Desktop View : -
image

Mobile View : -
image

### CODE REVIEW

**Comment by roshan1999** [comment]
Fix mobile screen

**Comment by AdityaTanejaRox** [comment]
I made a few css changes : - 

For laptop - 1440 
image



For laptop - 1024
image



For tablet - 768
image


Please check and accept PR

**Comment by roshan1999** [comment]
In Tablet screen size make the heading and sub heading bigger and center aligned to the screen

**Comment by roshan1999** [comment]
In laptop screen the text for about the picture is wrapping. Make sure u give it enough space so that it doesn't wrap

**Pull request closed without merging**
